### ISSUE TITLE
Orca Estimator checklist

### ISSUE THREAD

**Issue by cyita** [intel-analytics/analytics-zoo#3253]
**Spark Estimator**

1. TFOptimizerWrapper

- [ ] get_model

2. TFKerasWrapper

- [ ] get_model

3. PyTorchSparkEstimatorWrapper

- [ ] save

**Ray Estimator**

1. PyTorchRayEstimatorWrapper

- [ ] predict
- [ ] clear_gradient_clipping
- [ ] set_constant_gradient_clipping
- [ ] set_l2_norm_gradient_clipping
- [ ] get_train_summary
- [ ] get_validation_summary
- [ ] set_tensorboard ?

2. TFRayEstimator

- [ ] fit, predict, evaluate batch_size as param
- [ ] clear_gradient_clipping
- [ ] set_constant_gradient_clipping
- [ ] set_l2_norm_gradient_clipping
- [ ] get_train_summary
- [ ] get_validation_summary
- [ ] set_tensorboard ?

3. MXNetEstimator

- [ ] predict
- [ ] evaluate
- [ ] get_model
- [ ] save
- [ ] load
- [ ] clear_gradient_clipping
- [ ] set_constant_gradient_clipping
- [ ] set_l2_norm_gradient_clipping
- [ ] get_train_summary
- [ ] get_validation_summary
- [ ] set_tensorboard ?

**Comment by yangw1234** [comment]
@jason-dai 
For `TFOptimizerWrapper`, there is no "model" object to return, the model is represented as the current default graph and variable value in the current session.

For `TFKerasWrapper`, I think this is relatively easy to implement.

**Comment by yangw1234** [comment]
After #3337 Current Status 
|                 |Spark TF                          | Spark Keras           | Spark PyTorch           | Ray Keras               | Ray PyTorch            |  Ray MXNet|
|--|--|--|--|--|--|--|
|get_model| not going to implement|return keras model| return torch model    |  return keras model | return torch model| not yet implemented|
|save          | save as tf checkpoint     | save as keras h5   | not yet implemented | pickled serialized model weights| torch.save state dict| not yet implemented|
|load          | load orca checkpoint     | load orca checkpoint| load orca checkpoint|load what saved | load what saved| not yet implemented|
|fit |  xshard, dataframe, tf.data.dataset| xshard, dataframe, tf.data.dataset| xshard, dataloader, function no args to dataloader| xshard, dataframe, function one arg to dataset| xshard, function one arg to dataloader| xshard, function two args to mxnet dataloader|
|predict|xshard, dataframe| xshard, dataframe|xshard|xshard, dataframe| not yet implemented| not yet implemented|
|evaluate|xshard, dataframe, tf.data.dataset| xshard, dataframe,tf.data.dataset| xshard, dataloader, function no arg to dataloader|xshard, dataframe, function one arg to dataset| not yet implemented| not yet implemented|
