### ISSUE TITLE
Unify Orca Estimators predict methods

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/analytics-zoo#3348]
## Current Issue
1. some estimator does not support predict
2. different estimators' predict method has different support data format.
3. different estimators' predict method might return different data format. (needs to check)

## Proposal
1. all estimator should support predict on xshards and dataframe
2. for the input xshards each shard should be a dictionary with a key "x", the value is a single or a tuple of ndarrays. The returned xshard should have an additional "pred" key, and the value is a single or a tuple of ndarrays.
3. for the input dataframe, user should also specify another argument "feature_cols", which is a list strings indicating which columns to use for predict. The returned dataframe should have an additional "pred" column. (need to figure out how to deal with multiple predictions, and prediction has more than one dimension)

## Tasks
- [ ] Support dataframe spark pytorch estimator predict 
- [ ] Support predict in ray pytorch estimator
- [ ] Support predict in ray mxnet estimator
- [ ] unify xshard input formats and return formats
- [ ] unify dataframe input formats and return formats
