### ISSUE TITLE
Automl leaderboard usage improvement

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/analytics-zoo#3426]
Some issues/bugs needs to be fixed:

- [x] AutoTS should involve a param called `name` which helps the user to find the log files (#3434 )
- [x] Sorting malfunction in Tensorboard (#4620 )
- [x] Add additional address column (#3434 )
- [x] Each iter's result should be recorded (#3434 )
- [x] Remove the conditional import for tensorboardx (#3434 )
- [x] Change setup and doc tensorboardx version from 2.0 to 2.1

**Comment by TheaperDeng** [comment]
For the Sorting malfunction in Tensorboard, native ray tune does not have this issue.
